CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(50) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id),
  CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(250) NOT NULL,
  email varchar(254) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  pinned bool NOT NULL DEFAULT false,
  title varchar(50) NOT NULL,
  CONSTRAINT pk_compilation PRIMARY KEY (id),
  CONSTRAINT uq_compilation_name UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  annotation varchar(2000) NOT NULL,
  category_id bigint NOT NULL,
  created timestamp NOT NULL,
  description varchar(7000) NOT NULL,
  event_date timestamp NOT NULL,
  initiator_id bigint NOT NULL,
  lat float NOT NULL,
  lon float NOT NULL,
  paid bool NOT NULL,
  participant_limit integer NOT NULL DEFAULT 0,
  published timestamp,
  request_moderation bool NOT NULL DEFAULT true,
  state varchar(20),
  title varchar(120) NOT NULL,
  CONSTRAINT pk_event PRIMARY KEY (id),
  CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories (id),
  CONSTRAINT fk_event_initiator FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS compilation_events (
  compilation_id bigint,
  event_id bigint,
  CONSTRAINT pk_compilation_event PRIMARY KEY (compilation_id, event_id),
  CONSTRAINT fk_compilation_event_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id),
  CONSTRAINT fk_compilation_event_event FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created timestamp NOT NULL,
  event_id bigint NOT NULL,
  requester_id bigint NOT NULL,
  status varchar(20),
  CONSTRAINT pk_request PRIMARY KEY (id),
  CONSTRAINT uq_request UNIQUE (requester_id, event_id),
  CONSTRAINT fk_request_event FOREIGN KEY (event_id) REFERENCES events (id),
  CONSTRAINT fk_request_requester FOREIGN KEY (requester_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  text varchar(7000) NOT NULL,
  created timestamp NOT NULL,
  event_id bigint NOT NULL,
  author_id bigint NOT NULL,
  CONSTRAINT pk_comment PRIMARY KEY (id),
  CONSTRAINT fk_comment_event FOREIGN KEY (event_id) REFERENCES events (id),
  CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES users (id)
);
